buildscript {
    repositories {
		mavenCentral()
		maven { url = "https://plugins.gradle.org/m2" }
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = "https://repo.spongepowered.org/maven" }
		maven { url = "https://repo.spongepowered.org/repository/forge-proxy/" }
		//maven { url = 'https://maven.daporkchop.net/' }
    }
    dependencies {
		classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '4.0.+', changing: true
		classpath "org.spongepowered:mixingradle:0.7-SNAPSHOT"
	}
}
apply plugin: 'net.minecraftforge.gradle'
apply plugin: "org.spongepowered.mixin"
apply plugin: 'idea'

//Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.

sourceCompatibility = targetCompatibility = 1.8

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

version = "1.12.2"
group = "main" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "All"

repositories {	
	mavenLocal()
	maven { url = "https://repo.spongepowered.org/maven" }
    maven { url "https://www.cursemaven.com" }
	maven {
        name = "chickenbones"
        url = "https://maven.covers1624.net/" //"https://chickenbones.net/maven" //or https://maven.covers1624.net/
    }
	mavenCentral()
	
	flatDir {
		dir 'libs'
	}
}

minecraft {
    mappings channel: 'stable', version: '39-1.12'
	
	accessTransformer = file('src/main/resources/META-INF/gcgsac_at.cfg')
	
	  runs {
        client {
            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            // The markers can be changed as needed.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            property 'forge.logging.markers', 'REGISTRIES'

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            property 'forge.logging.console.level', 'debug'

			//args '-Dfml.coreMods.load=galaxyspace.core.hooks.GSHooksLoader,starmaker.utils.asm.AssetPlugin'
			args '-torg.spongepowered.asm.launch.MixinTweaker', '--mixin', 'mixins.galaxyspace.json', '-Dnet.minecraftforge.gradle.test_certs=false'
        }
        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
			property 'forge.logging.console.level', 'debug'
			//args '--tweakClass', 'org.spongepowered.asm.launch.MixinTweaker', '--mixin', 'mixins.test.json'
		}
        data {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
			property 'forge.logging.console.level', 'debug'
			args '--mod', 'chaindestruction', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

        }
    }
}

dependencies {

	minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'

	implementation "org.spongepowered:mixin:0.8.5"
	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
	testAnnotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

	implementation files('libs/buildcraft-api-7.99.24.8.jar')
	implementation files('libs/industrialcraft-2-2.8.222-ex112-api.jar')
	implementation files('libs/CraftTweaker2-1.12-4.1.20.696.jar')


	implementation files('libs/jei_1.12.2-4.13.1.220.jar')
	implementation files('libs/Mekanism-1.12.2-9.4.13.349-api.jar')
	implementation files('libs/PlanetProgression-1.12.2-0.4.8-api.jar')
	implementation files('libs/RedstoneFlux-1.12-2.1.0.6-universal.jar')
	
	compileOnly fg.deobf("libs:CodeChickenLib-1.12.2:3.2.3.358:universal")
	implementation files("libs/AsmodeusCore-1.12.2-1.0.4-dev.jar")
	implementation fg.deobf("libs:Galacticraft-1.12.2:4.0.2.283")

	//runtimeOnly fileTree('lib') { include '*.jar' }
	//compileOnly fileTree('libs')
}

idea {	module { inheritOutputDirs=true }}


jar {
    //manifest.attributes('FMLAT': 'gs_at.cfg')
	manifest {
		attributes([
				"Implementation-Title"    : project.name,
				"Implementation-Version"  : project.version,
				"TweakClass": "org.spongepowered.asm.launch.MixinTweaker",
				"MixinConfigs": "mixins.asmodeuscore.json,mixins.galaxyspace.json",
				"FMLCorePluginContainsFMLMod": "true",
				"FMLAT": "gcgsac_at.cfg",
				"ForceLoadAsMod": "true",
				"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
}

// Include resources generated by data generators.
sourceSets { main { output.resourcesDir = output.classesDirs.singleFile }}
sourceSets.main.resources { srcDir 'src/generated/resources' }

jar.finalizedBy('reobfJar')

processResources {
	inputs.property "version", project.version
	inputs.property "mcversion", "1.12.2"

	from(sourceSets.main.resources.srcDirs) {
		include 'mcmod.info'

		// replace version and mcversion
		expand 'version':project.version, 'mcversion':"1.12.2"
	}

	// copy everything else except the mcmod.info
	from(sourceSets.main.resources.srcDirs) {
		exclude 'mcmod.info'
	}
}

tasks.register('gsJar', Jar) {

	from(zipTree("build/libs/" + archivesBaseName + "-" + project.version + ".jar")) {
		exclude 'asmodeuscore/**'
		exclude 'assets/asmodeuscore/**'
		exclude 'beyondspace/**'
		exclude 'assets/beyondspace/**'
		exclude 'starmaker/**'
		exclude 'assets/starmaker/**'
		exclude 'spaceambient/**'
		exclude 'assets/spaceambient/**'
	}
	
	archiveFileName = "GalaxySpace-${project.version}.jar"

	manifest {
		attributes([
				"Implementation-Title"    : project.name,
				"Implementation-Version"  : project.version,
				"TweakClass": "org.spongepowered.asm.launch.MixinTweaker",
				"MixinConfigs": "mixins.galaxyspace.json",
				"FMLCorePluginContainsFMLMod": "true",
				"FMLAT": "gcgsac_at.cfg",
				"ForceLoadAsMod": "true",
				"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
}

tasks.register('deobfGSJar', Jar) {
	
	from(sourceSets.main.output)
	{
		exclude 'assets/**'
		exclude 'asmodeuscore/**'
		exclude 'beyondspace/**'
		exclude 'starmaker/**'
		exclude 'spaceambient/**'
		exclude 'mcmod.info'
	}
	from(sourceSets.main.allSource)
	{
		exclude 'asmodeuscore/**'
		exclude 'beyondspace/**'
		exclude 'starmaker/**'
		exclude 'assets/asmodeuscore/**'
		exclude 'assets/beyondspace/**'
		exclude 'assets/starmaker/**'
		exclude 'spaceambient/**'
		exclude 'assets/spaceambient/**'
	}

	archiveFileName = "GalaxySpace-${project.version}-dev.jar"

	manifest {
		attributes([
				"Implementation-Title"    : project.name,
				"Implementation-Version"  : project.version,
				"TweakClass": "org.spongepowered.asm.launch.MixinTweaker",
				"MixinConfigs": "mixins.galaxyspace.json",
				"FMLCorePluginContainsFMLMod": "true",
				"FMLAT": "gcgsac_at.cfg",
				"ForceLoadAsMod": "true",
				"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
	//manifest.attributes('FMLAT': 'gcgsac_at.cfg')
	//manifest.attributes('FMLCorePlugin': 'galaxyspace.core.hooks.GSHooksLoader')
	//manifest.attributes('FMLCorePluginContainsFMLMod': 'true')
}
