package galaxyspace.systems.SolarSystem.planets.overworld.tile;

import java.util.HashSet;
import java.util.Set;

import cpw.mods.fml.relauncher.Side;
import micdoodle8.mods.galacticraft.api.block.ITerraformableBlock;
import micdoodle8.mods.galacticraft.core.blocks.GCBlocks;
import micdoodle8.mods.galacticraft.core.energy.item.ItemElectricBase;
import micdoodle8.mods.galacticraft.core.energy.tile.EnergyStorageTile;
import micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlockWithInventory;
import micdoodle8.mods.galacticraft.core.network.IPacketReceiver;
import micdoodle8.mods.galacticraft.core.util.ConfigManagerCore;
import micdoodle8.mods.galacticraft.core.util.GCCoreUtil;
import micdoodle8.mods.galacticraft.planets.asteroids.blocks.AsteroidBlocks;
import micdoodle8.mods.galacticraft.planets.mars.blocks.MarsBlocks;
import micdoodle8.mods.miccore.Annotations.NetworkedField;
import net.minecraft.block.Block;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.inventory.ISidedInventory;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraftforge.common.util.ForgeDirection;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidContainerRegistry;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.fluids.FluidTank;
import net.minecraftforge.fluids.FluidTankInfo;
import net.minecraftforge.fluids.IFluidHandler;

public class TileEntityConverterSurface extends TileBaseElectricBlockWithInventory implements IFluidHandler, ISidedInventory, IPacketReceiver
{
    //The electric furnace is 50% faster than a vanilla Furnace
    //but at a cost of some inefficiency:
    //It uses 46800 gJ to smelt 8 ingots quickly
    //compared with the energy generated by 1 coal which is 38400 gJ
    //
    //The efficiency can be increased using a Tier 2 furnace

    public static int PROCESS_TIME_REQUIRED = 130;

    @NetworkedField(targetSide = Side.CLIENT)
    public int processTimeRequired = PROCESS_TIME_REQUIRED;

    @NetworkedField(targetSide = Side.CLIENT)
    public int processTicks = 0;

    private final int tankCapacity = 3000;
    @NetworkedField(targetSide = Side.CLIENT)
    public FluidTank waterTank = new FluidTank(this.tankCapacity);    
    
    private ItemStack[] containingItems = new ItemStack[6];
    public final Set<EntityPlayer> playersUsing = new HashSet<EntityPlayer>();

    private boolean initialised = false;

    public static ItemStack[] blocks = new ItemStack[] {   	

    	new ItemStack(GCBlocks.blockMoon, 1, 3),
    	new ItemStack(GCBlocks.blockMoon, 1, 4),
    	new ItemStack(GCBlocks.blockMoon, 1, 5),
    	new ItemStack(MarsBlocks.marsBlock, 1, 5),
    	new ItemStack(MarsBlocks.marsBlock, 1, 5),
    	new ItemStack(AsteroidBlocks.blockBasic, 1, 0),
    	new ItemStack(AsteroidBlocks.blockBasic, 1, 1),
    	new ItemStack(AsteroidBlocks.blockBasic, 1, 2),
    	/*
		new ItemStack(GSBlocks.MercuryBlocks, 1, 0),
		new ItemStack(GSBlocks.MercuryBlocks, 1, 1),
		new ItemStack(GSBlocks.MercuryBlocks, 1, 2),		
		new ItemStack(GSBlocks.VenusBlocks, 1, 0),
		new ItemStack(GSBlocks.VenusBlocks, 1, 1),
		new ItemStack(GSBlocks.CeresBlocks, 1, 0),
		new ItemStack(GSBlocks.CeresBlocks, 1, 1),
		new ItemStack(GSBlocks.PlutoBlocks, 1, 0),
		new ItemStack(GSBlocks.PlutoBlocks, 1, 1),
		new ItemStack(GSBlocks.PlutoBlocks, 1, 2),
		new ItemStack(GSBlocks.PlutoBlocks, 1, 3),
		new ItemStack(GSBlocks.PlutoBlocks, 1, 4),
		new ItemStack(GSBlocks.PlutoBlocks, 1, 5),
		new ItemStack(GSBlocks.HaumeaBlocks, 1, 0),
		new ItemStack(GSBlocks.MakemakeBlocks, 1, 0),
		new ItemStack(GSBlocks.MakemakeBlocks, 1, 1),
		new ItemStack(GSBlocks.PhobosBlocks, 1, 0),
		new ItemStack(GSBlocks.PhobosBlocks, 1, 1),
		new ItemStack(GSBlocks.PhobosBlocks, 1, 2),
		new ItemStack(GSBlocks.DeimosBlocks, 1, 0),
		new ItemStack(GSBlocks.DeimosBlocks, 1, 1),
		new ItemStack(GSBlocks.IoBlocks, 1, 0),
		new ItemStack(GSBlocks.IoBlocks, 1, 1),
		new ItemStack(GSBlocks.IoBlocks, 1, 2),
		new ItemStack(GSBlocks.EuropaBlocks, 1, 0),
		new ItemStack(GSBlocks.GanymedeBlocks, 1, 0),
		new ItemStack(GSBlocks.GanymedeBlocks, 1, 1),
		new ItemStack(GSBlocks.CallistoBlocks, 1, 0),
		new ItemStack(GSBlocks.CallistoBlocks, 1, 1),
		new ItemStack(GSBlocks.EnceladusBlocks, 1, 1),
		new ItemStack(GSBlocks.TitanBlocks, 1, 0),
		new ItemStack(GSBlocks.TitanBlocks, 1, 1),
		new ItemStack(GSBlocks.TitanBlocks, 1, 2),
		new ItemStack(GSBlocks.OberonBlocks, 1, 0),
		new ItemStack(GSBlocks.OberonBlocks, 1, 1),
		new ItemStack(GSBlocks.OberonBlocks, 1, 2),
		new ItemStack(GSBlocks.ProteusBlocks, 1, 0),
		new ItemStack(GSBlocks.ProteusBlocks, 1, 1),
		new ItemStack(GSBlocks.ProteusBlocks, 1, 2),
		new ItemStack(GSBlocks.TritonBlocks, 1, 0),
		new ItemStack(GSBlocks.TritonBlocks, 1, 1),
		new ItemStack(GSBlocks.TritonBlocks, 1, 2)	
    	*/
    };
    
    public TileEntityConverterSurface()
    {
        this(1);
    }

    /*
     * @param tier: 1 = Electric Furnace  2 = Electric Arc Furnace
     */
    public TileEntityConverterSurface(int tier)
    {
        this.initialised = true;
        if (tier == 1)
        {
            this.storage.setMaxExtract(ConfigManagerCore.hardMode ? 60 : 45);
            return;
        }

        this.setTier2();
    }
    
    private void setTier2()
    {
        this.storage.setCapacity(25000);
        this.storage.setMaxExtract(ConfigManagerCore.hardMode ? 90 : 60);
        this.processTimeRequired = 100;
        this.setTierGC(2);   	
    }

    public int getScaledWaterLevel(int i)
    {
         return this.waterTank.getFluidAmount() * i / this.waterTank.getCapacity();
    }
    
    @Override
    public void updateEntity()
    {
        if (!this.initialised )
        {
            int metadata = this.getBlockMetadata();
            //for version update compatibility
            Block b = this.worldObj.getBlock(this.xCoord, this.yCoord, this.zCoord);
            if (b == GCBlocks.machineBase)
            {
                this.worldObj.setBlock(this.xCoord, this.yCoord, this.zCoord, GCBlocks.machineTiered, 4, 2);
            }
            else if (metadata >= 8)
            {
            	this.setTier2();
            }
            this.initialised = true;
        }

        super.updateEntity();

        if (!this.worldObj.isRemote)
        {

                if (this.containingItems[1] != null)
                {
                	 FluidStack liquid = FluidContainerRegistry.getFluidForFilledItem(this.containingItems[1]);
                		
 	                if (liquid != null)
 	                {
 	                	boolean isWater = FluidRegistry.getFluidName(liquid).startsWith("water");
 		
 		                if (isWater)
 		                {
 		                    if (this.waterTank.getFluid() == null || this.waterTank.getFluid().amount + liquid.amount <= this.waterTank.getCapacity())
 		                    {
 		                        this.waterTank.fill(new FluidStack(FluidRegistry.WATER, liquid.amount), true);
 		
 		                        if (FluidContainerRegistry.isBucket(this.containingItems[1]) && FluidContainerRegistry.isFilledContainer(this.containingItems[1]))
 		                        {
 		                            final int amount = this.containingItems[1].stackSize;
 		                            if (amount > 1) this.waterTank.fill(new FluidStack(FluidRegistry.WATER, (amount - 1) * FluidContainerRegistry.BUCKET_VOLUME), true);
 		                            this.containingItems[1] = new ItemStack(Items.bucket, amount);
 		                        }
 		                        else
 		                        {
 		                            this.containingItems[1].stackSize--;
 		
 		                            if (this.containingItems[1].stackSize == 0)
 		                            {
 		                                this.containingItems[1] = null;
 		                            }
 		                        }
 		                    }
 		                }
 	                }
                }
                
            if (this.canProcess())
            {
               if (this.hasEnoughEnergyToRun)
                {
                    //50% extra speed boost for Tier 2 machine if powered by Tier 2 power
                    if (this.tierGC == 2) this.processTimeRequired = 200 / (1 + this.poweredByTierGC);

                    if (this.processTicks == 0)
                    {
                        this.processTicks = this.processTimeRequired;
                    }
                    else
                    {
                        if (--this.processTicks <= 0)
                        {
                            this.smeltItem();
                            this.processTicks = this.canProcess() ? this.processTimeRequired : 0;
                        }
                    }
                }
                else if (this.processTicks > 0 && this.processTicks < this.processTimeRequired)
                {
                    //Apply a "cooling down" process if the electric furnace runs out of energy while smelting
                    if (this.worldObj.rand.nextInt(4) == 0)
                    {
                        this.processTicks++;
                    }
                }
            }
            else
            {
                this.processTicks = 0;
            }
            
        }
    }

    /**
     * @return Is this machine able to process its specific task?
     */
    public boolean canProcess()
    {
    	if (this.waterTank.getFluidAmount() == 0)
        {
      		return false;
        }
    	if(this.containingItems[2] == null || this.containingItems[3] == null || this.containingItems[4] == null)
    	{
    		return false;
    	}
    	
    	if (this.containingItems[4] != null)
    	{
    		Block block = Block.getBlockFromItem(this.containingItems[4].getItem());
    		if(!(block instanceof ITerraformableBlock)) return false;
    	}
    	if (this.containingItems[5] != null)
    	{
    		if (this.containingItems[5].stackSize + 1 > 64)
    		{
    			return false;
    		}
    	}
	
    	return true;
    }

    /**
     * Turn one item from the furnace source stack into the appropriate smelted
     * item in the furnace result stack
     */
    public void smeltItem()
    {
        if (this.canProcess())
        {
           
            if (this.containingItems[5] == null) this.containingItems[5] = new ItemStack(Blocks.grass);
            else this.containingItems[5].stackSize++;  
            
            this.waterTank.drain(100, true);
            
            if (--this.containingItems[2].stackSize <= 0)
        	{
                this.containingItems[2] = null;
            }
        	if (--this.containingItems[3].stackSize <= 0)
        	{
                this.containingItems[3] = null;
            }
        	if (--this.containingItems[4].stackSize <= 0)
        	{
                this.containingItems[4] = null;
            }
           
        }
    }

    @Override
    public void readFromNBT(NBTTagCompound par1NBTTagCompound)
    {
        super.readFromNBT(par1NBTTagCompound);
        if (this.storage.getEnergyStoredGC() > EnergyStorageTile.STANDARD_CAPACITY)
        {
        	this.setTier2();
        	this.initialised = true;
        }
        else
        	this.initialised = false;
        this.processTicks = par1NBTTagCompound.getInteger("smeltingTicks");
        this.containingItems = this.readStandardItemsFromNBT(par1NBTTagCompound);
        
        if (par1NBTTagCompound.hasKey("waterTank"))
        {
            this.waterTank.readFromNBT(par1NBTTagCompound.getCompoundTag("waterTank"));
        }
    }

    @Override
    public void writeToNBT(NBTTagCompound par1NBTTagCompound)
    {
        if (this.tierGC == 1 && this.storage.getEnergyStoredGC() > EnergyStorageTile.STANDARD_CAPACITY)
        	this.storage.setEnergyStored(EnergyStorageTile.STANDARD_CAPACITY);
    	super.writeToNBT(par1NBTTagCompound);
        par1NBTTagCompound.setInteger("smeltingTicks", this.processTicks);
        this.writeStandardItemsToNBT(par1NBTTagCompound);
        if (this.waterTank.getFluid() != null)
        {
            par1NBTTagCompound.setTag("waterTank", this.waterTank.writeToNBT(new NBTTagCompound()));
        }
    }

    @Override
    protected ItemStack[] getContainingItems()
    {
        return this.containingItems;
    }

    @Override
    public String getInventoryName()
    {
        return GCCoreUtil.translate("tile.ConverterSurface.name");
    }

    @Override
    public boolean hasCustomInventoryName()
    {
        return true;
    }

    /**
     * Returns true if automation is allowed to insert the given stack (ignoring
     * stack size) into the given slot.
     */
    @Override
    public boolean isItemValidForSlot(int slotID, ItemStack itemStack)
    {
        if (itemStack == null) return false;
        if(slotID == 0) return ItemElectricBase.isElectricItem(itemStack.getItem());
        if(slotID == 1) return itemStack.getItem() == new ItemStack(Items.water_bucket).getItem();
        if(slotID == 2) return itemStack.getItem() == new ItemStack(Items.dye, 1, 15).getItem();
        if(slotID == 3) return itemStack.getItem() == new ItemStack(Items.wheat_seeds).getItem();
        if(slotID == 4) 
        {
        		return true;
        }
       /* for (ItemStack i : blocks)
		{
        	if(slotID == 4) return itemStack == i;
		}*/
    	return false;
    }

    @Override
    public int[] getAccessibleSlotsFromSide(int side)
    {
        return new int[] {0, 2, 3, 4, 5 };
    }

    @Override
    public boolean canInsertItem(int slotID, ItemStack par2ItemStack, int par3)
    {
        return this.isItemValidForSlot(slotID, par2ItemStack);
    }

    @Override
    public boolean canExtractItem(int slotID, ItemStack par2ItemStack, int par3)
    {
        return slotID == 5;
    }

    @Override
    public boolean shouldUseEnergy()
    {
        return this.canProcess();
    }

    @Override
    public int fill(ForgeDirection from, FluidStack resource, boolean doFill)
    {
        int used = 0;

        if (from.equals(ForgeDirection.getOrientation(this.getBlockMetadata() + 2).getOpposite()))
        {
            final String liquidName = FluidRegistry.getFluidName(resource);

            if (liquidName != null && liquidName.startsWith("water")) used = this.waterTank.fill(resource, doFill);
        }

        return used;
    }

    @Override
	public FluidStack drain(ForgeDirection from, FluidStack resource, boolean doDrain) 
	{
		return null;
	}

	@Override
	public FluidStack drain(ForgeDirection from, int maxDrain, boolean doDrain)
	{
		return null;
	}

	@Override
    public boolean canFill(ForgeDirection from, Fluid fluid)
    {
        return this.waterTank.getFluid() == null || this.waterTank.getFluidAmount() < this.waterTank.getCapacity();
    }

    @Override
    public boolean canDrain(ForgeDirection from, Fluid fluid)
    {
        return false;
    }

	@Override
    public FluidTankInfo[] getTankInfo(ForgeDirection from)
    {
        return new FluidTankInfo[] { new FluidTankInfo(this.waterTank) };
    }
}